application:
  name: waitlisted-api
  project: appixel-waitlisted
  cloud_region: aws/us-east-2
  publicly_accessible: true
routers:
- name: main
  custom_domains:
    - branch: master
      domain: waitlisted.appixel.dev
  routes:
  - application_name: waitlisted-api
    paths:
    - /api/